/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

public class App {

    public static void main(String[] args) throws Exception {

        Options options = new Options();

        Option help = Option.builder("h").longOpt("help").desc("print usage message").build();
        help.setRequired(false);
        options.addOption(help);

        Option batch = Option.builder("b").longOpt("batch").argName("file").hasArg().desc("batch file containing expressions to evaluate").build();
        batch.setRequired(false);
        options.addOption(batch);

        Option output = Option.builder("o").longOpt("output").argName("file").hasArg().desc("output file").build();
        output.setRequired(false);
        options.addOption(output);

        HelpFormatter formatter = new HelpFormatter();
        CommandLineParser parse = new DefaultParser();

        CommandLine cmd;

        try {

            cmd = parse.parse(options, args);

            if(cmd.hasOption("h") || cmd.hasOption("help")) {
                formatter.printHelp("app  [OPTIONS] \nEvaluation of simple mathematical expressions", options);
            }

            if(cmd.hasOption("b") || cmd.hasOption("batch")) {
                System.out.println("Batch file: " + cmd.getOptionValue("batch"));
            }

            if(cmd.hasOption("o") || cmd.hasOption("output")) {
                System.out.println("Output file: " + cmd.getOptionValue("output"));
            }



        } catch (ParseException e) {
            System.err.println("Parsing failed. Reason: " + e.getMessage());
            formatter.printHelp("app", options);
            System.exit(1);
        }

    }
}
